Repository COSIMA/access-om3, pull requests merged in 2023-11, with the labels that each got.

#84 Update WW3 swtiches and replace ww3_outp utility with ww3_ounp
  WW3/CMakeLists.txt
Labels: ww3

#87 Several fixes and library dependencies cleanup
  CDEPS/CMakeLists.txt
  CICE/CMakeLists.txt
  CMEPS/CMakeLists.txt
  CMakeLists.txt
  MOM6/CMakeLists.txt
  WW3/CMakeLists.txt
  share/CMakeLists.txt
Labels: build system

#80 Add option to install components as libraries
  CDEPS/CMakeLists.txt
  CICE/CMakeLists.txt
  CMEPS/CMakeLists.txt
  CMakeLists.txt
  MOM6/CMakeLists.txt
  WW3/CMakeLists.txt
  cmake/AccessOM3Config.cmake.in
  cmake/FortranLib.cmake
  share/CMakeLists.txt
Labels: enhancement, build system
